### DISCUSSION TITLE
How to run login before pulling docker images?

### DISCUSSION THREAD

**Discussion by zomars** [docker/login-action#669] [Q&A] [answered]
We have login action setup but when the job uses a services it tries to pull them before logging in. Causing rate limiting errors:

<img width="558" alt="image" src="https://github.com/docker/login-action/assets/3504472/8f5735c2-11ab-4f02-bf21-bbcad77acde7">

Is there a way to "login globally" or store credentials so we ensure credentials are being used?

**Comment by Ajay4087** [comment]
To resolve this issue, you need to ensure that the Docker login action runs before attempting to pull any images from Docker Hub. This way, Docker will recognize your authenticated session and remove the rate limiting restrictions.

To run the Docker login command before pulling images, you typically need to ensure that the `docker login` step precedes any steps that involve pulling images from a registry in your workflow or job configuration.

In the context of the image you provided, here's what you can do:

1. Locate the step or action that performs the `docker pull` operation in your workflow or job configuration file (e.g., GitHub Actions workflow, GitLab CI/CD pipeline, etc.).

2. Before that step, add a new step that runs the `docker login` command to authenticate with the Docker registry (e.g., Docker Hub).

For example, if you're using GitHub Actions, you can add a step like this before any steps that pull images:


steps:
  

```
- name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}


```
Replace `${{ secrets.DOCKERHUB_USERNAME }}` and `${{ secrets.DOCKERHUB_TOKEN }}` with the appropriate secrets or environment variables that store your Docker Hub credentials.

3. If you're using a different CI/CD tool or a custom script, you'll need to add the `docker login` command before any `docker pull` commands in your configuration or script.

By executing the `docker login` command before attempting to pull images, you'll authenticate with the Docker registry, and the subsequent pull requests should not be affected by the rate limiting errors.

Make sure to store your Docker registry credentials securely as secrets or environment variables in your CI/CD system, and avoid committing them to your codebase.
```

**Reply by zomars** [reply]
Thanks for the answer but this is not what I've asked. Basically when you use a `service` like a Postgres image:

```
 services:
      postgres:
        image: postgres:13
```

This runs BEFORE any step that you specified. So it tries to do a `docker pull` of the image before the `docker/login-action@v2` is even run.

**Comment by zomars** [comment, marked as answer]
Solved by passing credentials to the service itself:

```
    services:
      postgres:
        image: postgres:13
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
