### DISCUSSION TITLE
How to set http proxy ?

### DISCUSSION THREAD

**Discussion by seepine** [docker/login-action#853] [Q&A]
I encountered a similar problem  https://github.com/docker/login-action/issues/146
I try but not work
```yml
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
      env:
        HTTP_PROXY: ${{ env.http_proxy }}
        HTTPS_PROXY: ${{ env.https_proxy }}
        NO_PROXY: ${{ env.no_proxy }}
```

```
Logging into Docker Hub...
::error::Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
