### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by eblot** [docker/login-action#104]
#### Steps to reproduce this issue

Add docker/login-action to workflow, start the workflow

#### Expected behaviour

Expect successful login on Docker registry.
No idea on how to diagnose this early error.

#### Actual behaviour

```
Error : .github#L1
docker/login-action@v1 is not allowed to be used in <organization>/<repo>. Actions in this workflow must be: within a repository owned by <organization> or created by GitHub.
```

### Configuration

Private.

```yml
jobs:
  go:
    name: Build & Test Actions
    runs-on: [self-hosted]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

### Logs

> Download the [log file of your build]

There is no log file

<img width="1044" alt="Screenshot 2021-09-30 at 15 22 23" src="https://user-images.githubusercontent.com/172423/135463220-2a95eb5f-6c1c-47e5-963b-5e36532761bf.png">

**Comment by crazy-max** [comment]
@eblot 

> ```
> docker/login-action@v1 is not allowed to be used in <organization>/<repo>. Actions in this workflow must be: within a repository owned by <organization> or created by GitHub.
> ```

Not linked to this action but permissions in your organization. I suggest to contact the administrator of the organization or you can open a support ticket to GitHub about this: https://support.github.com/contact

**Comment by eblot** [comment]
Note: replacing login-action with CLI does work:
```yaml
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }}
                          -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logout from Docker Hub
        if: always()
        run: docker logout

```
