### ISSUE TITLE
Cannot login to private registry that doesn't have routes for api versions

### ISSUE THREAD

**Issue by sesopenko** [docker/login-action#105]
### Behaviour

Fails to login to private registry

#### Steps to reproduce this issue

1. Declare a `registry` parameter pointing to a private registry. ie:  `https://docker.seanesopenko.ca`
2. Run github action

#### Expected behaviour

Logs in to registry

#### Actual behaviour

Fails to log in, with a 403 forbidden error.  Appends `/v2` to the url, assuming all registries have routes for docker registry api versions. Example output in the github action console.

```
Run docker/login-action@v1
Logging into https://docker.seanesopenko.ca...
Error: Error response from daemon: login attempt to https://docker.seanesopenko.ca/v2/ failed with status: 403 Forbidden
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Orchestration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        # ref: https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
[action_log.txt](https://github.com/docker/login-action/files/7271940/action_log.txt)

          go-version: 1.16

      - name: Go Build
        run: go run mage.go build

      - name: Go Test
        run: go run mage.go test
      # see https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: https://docker.seanesopenko.ca
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push master image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.seanesopenko.ca/multiplayer-orchestration:latest
      - name: Build and push pr image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.seanesopenko.ca/multiplayer-orchestration:${{ steps.extract_branch.outputs.branch }}
```

### Logs

attached
