### ISSUE TITLE
Use AWS ECR login method with a custom domain

### ISSUE THREAD

**Issue by pawelmitka** [docker/login-action#107]
### Behaviour
Currently the ECR [login method](https://github.com/docker/login-action/blob/9e433e18cfff6656177a0cfc925831e79957ed84/src/docker.ts#L6) depends on [isEcr](https://github.com/docker/login-action/blob/9e433e18cfff6656177a0cfc925831e79957ed84/src/aws.ts#L7) which verifies an address. However, we would like to use a custom domain with ECR to simplify our Dockerfiles.

#### Steps to reproduce this issue
1. Create an action in workflow with a custom domain for ECR private registry
2. Run workflow

#### Expected behaviour
Action correctly logins to ECR despite custom address using [loginECR](https://github.com/docker/login-action/blob/9e433e18cfff6656177a0cfc925831e79957ed84/src/docker.ts#L53)

#### Actual behaviour
login-action does not login to ECR using [loginECR](https://github.com/docker/login-action/blob/9e433e18cfff6656177a0cfc925831e79957ed84/src/docker.ts#L53)

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
     - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: custom.io
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

### Solution
I think, it would be the best to add an optional flag `isECR` to the configuration to allow use of ECR login despite custom domain usage.

**Comment by crazy-max** [comment]
@pawelmitka Can you try with?:

```yaml
     - name: Login to ECR
        uses: crazy-max/docker-login-action@ecr-input
        with:
          registry: custom.io
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecr: true
```
