### ISSUE TITLE
is it possible to use docker/login-action as authentication for subsequent curl commands

### ISSUE THREAD

**Issue by udos** [docker/login-action#113]
I would like to run some curl commands towards the docker hub registry and was curious if this is possible with docker/login-action and if yes, how to do it.

doing this was not successful:

```yml
# list public repos
- name: list docker repositories (not authenticated)
  run: curl https://hub.docker.com/v2/repositories/my_repo | jq -r -C .
- uses: docker/login-action@v1
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
# list public and private repos
- name: list docker repositories (authenticated)
  run: curl https://hub.docker.com/v2/repositories/my_repo | jq -r -C .
```

**Comment by crazy-max** [comment]
No you cannot use the login action to make API requests to Docker Hub. You have to create an authentication token as [stipulated in the docs](https://docs.docker.com/docker-hub/api/latest/#operation/PostUsersLogin).

You can something like this but I don't think it will not work if 2FA is enabled:

```yaml
    - name: List repositories
      run: |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' https://hub.docker.com/v2/users/login?refresh_token=true | jq -r .token)
```

Instead of curl requests, you could use the [hub-tool](https://github.com/docker/hub-tool).
