### ISSUE TITLE
Action fails on ARM64 self hosted runner

### ISSUE THREAD

**Issue by igorpecovnik** [docker/login-action#122]
### Behaviour

Permission denied while trying to connect to the Docker daemon socket

#### Steps to reproduce this issue

1. Using action on x86 runner works
2. Using action on arm64 runner fails (tested on many different ones)

#### Expected behaviour

It should login to the Github with the same way as it does on the x86 runner.

#### Actual behaviour

Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock

### Configuration

* [Repository URL](https://github.com/armbian/build) 
* [Build URL](https://github.com/armbian/build/runs/4544213952)

```yml
name: Build Docker Image
on:
  # Trigger the workflow on push but only for the main branch
  push:
    branches:
      - master
  # Trigger manually
  workflow_dispatch:

jobs:

  build-amd64:

    name: Build amd64 Docker image
    needs: build-arm64  
    
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:

     - uses: actions/checkout@v1

     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.CR_PAT }}
[logs_7652.zip](https://github.com/docker/login-action/files/7726883/logs_7652.zip)

```

**Comment by crazy-max** [comment]
> ```
> Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth: dial unix /var/run/docker.sock: connect: permission denied
> ```

Looks like an issue with Docker installation on your self-hosted runner.

**Comment by igorpecovnik** [comment]
> Looks like an issue with Docker installation on your self-hosted runner.

That was my first idea. As a normal user or root:

```arm-01:~:% docker run hello-world

Hello from Docker!```

Cleaned, repeated on different machines. The same.

**Comment by crazy-max** [comment]
@igorpecovnik Can you add this step before the login one and give me the output?:

```yaml
     - name: Docker info
       run: |
         docker version
         docker info
```
