### ISSUE TITLE
Login to Quay.io does not work

### ISSUE THREAD

**Issue by phracek** [docker/login-action#136]
### Behaviour
My GitHub Action looks like https://github.com/sclorg/s2i-base-container/blob/master/.github/workflows/build-and-push.yml

#### Steps to reproduce this issue

1. export secrets into GITHUB_ENVs
2. in username and password use: ${{ env.QUAY_TOKEN }} respectively ${{ env.QUAY_TOKEN }}
3. Login to Quay.io does not work.

See error from action:
```bash
Run docker/login-action@v1
  with:
    registry: quay.io
    ecr: auto
    logout: true
Error: Username and password required
```

Storing secrets in the matrix does not work.

#### Expected behaviour
Login is working properly.
> Tell us what should happen

#### Actual behaviour
Login does not work.
> Tell us what happens instead

### Configuration

* Repository URL (if public): https://github.com/sclorg/s2i-base-container/blob/master/.github/workflows/build-and-push.yml
* Build URL (if public): https://github.com/sclorg/s2i-base-container/runs/4762156878?check_suite_focus=true

```yml
      - name: Export GitHub secrets
        run: |
          if [ "${{ matrix.os_type }}" == "centos7" ]; then
            username="${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}"
            token="${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}"
          else
            username="${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}"
            token="${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN  }}"
          fi
          echo "QUAY_USERNAME=$username" >> GITHUB_ENV
          echo "QUAY_ROBOT_TOKEN=$token" >> GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_ROBOT_TOKEN }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by phracek** [comment]
@crazy-max @Flydiverny Can you please look at this issue, what is wrong? Is this a bug? Thank you.

**Comment by crazy-max** [comment]
@phracek 

Looking at the error `Error: Username and password required` inputs look empty.

> ```
> echo "QUAY_USERNAME=$username" >> GITHUB_ENV
> echo "QUAY_ROBOT_TOKEN=$token" >> GITHUB_ENV
> ```

Don't think you can store secrets in `GITUHB_ENV`.

Suggest to have condition steps instead:

```yaml
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io (centos7)
        if: matrix.os_type == 'centos7'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}

      - name: Login to Quay.io
        if: matrix.os_type != 'centos7'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN }}
```
