### ISSUE TITLE
AWS Auth does not include session token

### ISSUE THREAD

**Issue by daniel-farrell-blockfi** [docker/login-action#141]
### Behaviour

If used with short term AWS access tokens including a Session Token, the AWS ECR auth fails because the AWS integration interferes in the standard AWS credentials resolution process.

#### Steps to reproduce this issue

1. Use the aws-actions/configure-aws-credentials@master action with OIDC based role assumption (https://github.com/github/roadmap/issues/249).  
2. Use the docker/login-action action to attempt to auth to AWS

#### Expected behaviour

AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID, and AWS_SESSION_TOKEN should be used to authenticate the request.  

#### Actual behaviour

AWS_SESSION_TOKEN is omitted from the auth process because the code interferes with standard credentials resolution process.  

```
Run aws-actions/configure-aws-credentials@master
  with:
    role-to-assume: arn:aws:iam::0123456789:role/abcded-role-name
    role-session-name: github-actions
    aws-region: us-east-1
    
Run docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
  with:
    registry: ***.dkr.ecr.us-east-1.amazonaws.com
    username: AWS
    logout: true
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.1-12/x64
AWS ECR detected with us-east-1 region
Retrieving docker login command through AWS CLI 2.4.9 (/usr/local/bin/aws)...
Error: An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Run build

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
jobs:
  api:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::01234567890:role/github-automation
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: 01234567890.dkr.ecr.us-east-1.amazonaws.com
          username: AWS
```

### Logs

See above
