### ISSUE TITLE
Environment variable https_proxy is not used

### ISSUE THREAD

**Issue by svasek** [docker/login-action#146]
### Behaviour
Login to AWS ECR doesn't work if action is running behind http(s) proxy.

#### Steps to reproduce this issue

1. Run self-hosted runner in network environment with blocked internet connection which needs use http_proxy
2. Set Environment variables `http_proxy` and `https_proxy` to correct proxy server
3. Let login-action to login to (private) ECR
4. Error: connect ETIMEDOUT 52.119.173.252:443

#### Expected behaviour

> AWS ECR auth token should be retrieved with AWS SDK.

#### Actual behaviour

> ##[debug]Save intra-action state isPost = true
::save-state name=registry::***.dkr.ecr.us-west-2.amazonaws.com
##[debug]Save intra-action state registry = ***.dkr.ecr.us-west-2.amazonaws.com
::save-state name=logout::true
##[debug]Save intra-action state logout = true
Retrieving registries data through AWS SDK...
##[debug]Requesting AWS ECR auth token for ***
AWS ECR detected with us-west-2 region
Error: connect ETIMEDOUT 52.119.173.252:443
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to AWS ECR

### Configuration

* Repository URL (if public): private
* Build URL (if public): private

```yml
      - name: Configure AWS Credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to AWS ECR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REPO }}
```

**Comment by crazy-max** [comment]
@svasek Is the `uses: aws-actions/configure-aws-credentials@v1` step working?

**Comment by svasek** [comment]
> @svasek Is the `uses: aws-actions/configure-aws-credentials@v1` step working?

I'm not sure as I've added it because it didn't work.

**Comment by crazy-max** [comment]
Looking at [their docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html) it should be capitalize `HTTP_PROXY`, `HTTPS_PROXY` I think or maybe we need this kind of pkg: https://github.com/awslabs/aws-sdk-v3-js-proxy#readme

**Comment by svasek** [comment]
- The workflow fails in step `Login to AWS ECR`
- It doesn't work even when I set environment variables capitalised
- It doesn't work even when I use directly `docker/login-action` w/o `aws-actions/configure-aws-credentials`

**Comment by svasek** [comment]
Unfortunately it doesn't even when I tried it run directly:

```yaml
      - name: Login to AWS ECR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REPO }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          NO_PROXY: ${{ env.NO_PROXY }}
          HTTP_PROXY: ${{ env.PROXYURL }}
          HTTPS_PROXY: ${{ env.PROXYURL }} 
```   

Log output:

```
Run actions/docker-login-action@v1
::save-state name=isPost::true
##[debug]Save intra-action state isPost = true
::save-state name=registry::***.dkr.ecr.us-west-2.amazonaws.com
##[debug]Save intra-action state registry = ***.dkr.ecr.us-west-2.amazonaws.com
::save-state name=logout::true
##[debug]Save intra-action state logout = true
Retrieving registries data through AWS SDK...
##[debug]Requesting AWS ECR auth token for ***
AWS ECR detected with us-west-2 region
Error: connect ETIMEDOUT 54.240.253.186:443
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to AWS ECR
```

**Comment by svasek** [comment]
Hi @crazy-max, is there any update on this?

**Comment by crazy-max** [comment]
@svasek Oh sorry I completely forgot that one. Will setup smth this week!

**Comment by crazy-max** [comment]
@svasek Can you try with:

```yaml
      - name: Login to AWS ECR
        if: github.event_name != 'pull_request'
        uses: crazy-max/docker-login-action@aws-sdk-proxy
        with:
          registry: ${{ env.ECR_REPO }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          HTTP_PROXY: ${{ env.PROXYURL }}
          HTTPS_PROXY: ${{ env.PROXYURL }} 
```
