### ISSUE TITLE
Cannot consume authorization in following steps

### ISSUE THREAD

**Issue by twiddler** [docker/login-action#147]
#### Steps to reproduce this issue

1. Sign in with `docker/login-action@v1`
2. Try to pull a private image from within a `docker` image based container

#### Expected behaviour

Trying to pull the private image from within a `docker` image based container should work the same as executing `docker pull ghcr.io/twiddler/my-alpine:3.13` on the host.

#### Actual behaviour

> Error response from daemon: Head "https://ghcr.io/v2/twiddler/alpine/manifests/3.13": denied

Interestingly, the equivalent also fails on my local machine:

```console
$ docker login ghcr.io
...
$ docker run -v /var/run/docker.sock:/var/run/docker.sock docker pull ghcr.io/twiddler/my-alpine:3.13
Error response from daemon: Head "https://ghcr.io/v2/twiddler/my-alpine/manifests/3.13": unauthorized
```

while

```console
$ docker login ghcr.io
...
$ docker pull ghcr.io/twiddler/my-alpine:3.13
```

works as expected.

### Configuration

After reading #32 and #34, I came up with this `test.yml`:

```yml
on:
  push:

jobs:
  dind:
    runs-on: ubuntu-latest

    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker://docker
        with:
          entrypoint: docker
          args: pull "ghcr.io/twiddler/my-alpine:3.13"
```

### Logs

[logs_41.zip](https://github.com/docker/login-action/files/8028695/logs_41.zip)
