### ISSUE TITLE
Error: Must provide --username with --password-stdin

### ISSUE THREAD

**Issue by mristin** [docker/login-action#17]
Hi,
I tried to build a multi-arch image in a workflow based on this article: https://github.com/docker/build-push-action#multi-platform-image

However, when I run it, I get the error:

```
Error: Must provide --username with --password-stdin
```

Please see the full build log here: https://github.com/admin-shell-io/aasx-server/pull/41/checks?check_run_id=1264107244

**Comment by mristin** [comment]
I figured out the issue. The problem is that I didn't set up the username correctly. In my workflow I wrote:

```
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
```

whereas the secret was `DOCKERHUB_USER`, so the username was empty. However, the message is really misleading in this case:
```
Error: Must provide --username with --password-stdin
```

You probably need to do a more refined check here: https://github.com/docker/login-action/blob/master/src/docker.ts#L23:
```
  if (username) {
    loginArgs.push('--username', username);
  }
```
?

Is the standard loging *without* the username possible at all? Shouldn't an empty username already be a red flag and raise an exception?
