### ISSUE TITLE
Make this action compatible with aws-actions/configure-aws-credentials

### ISSUE THREAD

**Issue by dbuades** [docker/login-action#20]
### Behaviour

The official AWS action for setting up credentials works very well for assuming roles. Ideally, this action should be compatible with it. We have been using https://github.com/aws-actions/amazon-ecr-login for logging in, but it is not compatible with your new https://github.com/docker/build-push-action.

Something like this would be very useful:

```yml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-duration-seconds: 1200
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}

     - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ...
```

What do you think? Is there a known workaround to accomplish this? Thanks in advance!

**Comment by crazy-max** [comment]
@dbuades This action already handles [AWS Elastic Container Registry (ECR)](https://github.com/docker/login-action#aws-elastic-container-registry-ecr):

```yaml
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.ACCESS_KEY_ID }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}

     - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ...
```

If `role-*` are required on your side, then yes maybe we should be compatible with `aws-actions/configure-aws-credentials`.

**Comment by dbuades** [comment]
> @dbuades This action already handles [AWS Elastic Container Registry (ECR)](https://github.com/docker/login-action#aws-elastic-container-registry-ecr):
> 
> ```yaml
>       - name: Login to Amazon ECR
>         uses: docker/login-action@v1
>         with:
>           registry: ${{ secrets.ECR_REGISTRY }}
>           username: ${{ secrets.ACCESS_KEY_ID }}
>           password: ${{ secrets.SECRET_ACCESS_KEY }}
> 
>      - name: Build and push
>         id: docker_build
>         uses: docker/build-push-action@v2
>         with:
>           ...
> ```
> 
> If `role-*` are required on your side, then yes maybe we should be compatible with `aws-actions/configure-aws-credentials`.

Yes, that's what I meant, we need roles on our side and unfortunately this action doesn't support them.
I guess making this action compatible with  `aws-actions/configure-aws-credentials` is the easiest way to go, so that's why I suggested it.
Thanks and sorry if I didn't explain myself clearly!

**Comment by crazy-max** [comment]
@dbuades 

> Yes, that's what I meant, we need roles on our side and unfortunately this action doesn't support them.

My bad I read it wrong. Something like this should work in the meantime:

```yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-duration-seconds: 1200
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          username: ${{ secrets.ACCESS_KEY_ID }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}

     - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ...
```

[Env vars exported](https://github.com/aws-actions/configure-aws-credentials/blob/90247e87dda74e1722661cd5f9f024a4278839d9/index.js#L97-L140) by `aws-actions/configure-aws-credentials` for role assumption will be used through the [`ecr get-login` cmd](https://github.com/docker/login-action/blob/39ef12fb7a5c50dfb9aecd9d9834f0594197eaf2/src/aws.ts#L47)
