### ISSUE TITLE
Error: Username and password required

### ISSUE THREAD

**Issue by krishnaTORQUE** [docker/login-action#233]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

Should Login

#### Actual behaviour

Error: Username & Password required

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
- id: auth
  name: Auth
  uses: google-github-actions/auth@v0
  with:
    credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}

- name: Docker Login
  uses: docker/login-action@v2
  with:
    registry: gcr.io
    username: oauth2accesstoken
    password: ${{ steps.auth.outputs.access_token }}

```

### Logs
Run docker/login-action@v2
Error: Username and password required
