### ISSUE TITLE
Username and Password required 

### ISSUE THREAD

**Issue by iSolorak** [docker/login-action#236]
#### Steps to reproduce this issue

1. 
2.
3.

#### Expected behaviour

It should login me successfully  .

#### Actual behaviour

ERROR 5 : Username and password required

Also when i changed the credentials format to the actual dockerhub  username and token instead of ${{ secrets.DOCKERHUB_USERNAME }} , it logged in me correctly. But it is not possible to just upload your secret credentials to a public repo : D

### Configuration

```yml
---
name: Checks

on: [push]

jobs: 
 test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
```

### Logs
2022-07-10T17:22:23.9400128Z Requested labels: ubuntu-20.04
2022-07-10T17:22:23.9400174Z Job defined at: iSolorak/recipe-app-api/.github/workflows/checks.yml@refs/heads/main
2022-07-10T17:22:23.9400197Z Waiting for a runner to pick up this job...
2022-07-10T17:22:24.2725884Z Job is waiting for a hosted runner to come online.
2022-07-10T17:22:29.5112092Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2022-07-10T17:22:31.8313641Z Current runner version: '2.294.0'
2022-07-10T17:22:31.8347387Z ##[group]Operating System
2022-07-10T17:22:31.8348385Z Ubuntu
2022-07-10T17:22:31.8348632Z 20.04.4
2022-07-10T17:22:31.8348908Z LTS
2022-07-10T17:22:31.8349170Z ##[endgroup]
2022-07-10T17:22:31.8349920Z ##[group]Virtual Environment
2022-07-10T17:22:31.8350287Z Environment: ubuntu-20.04
2022-07-10T17:22:31.8350614Z Version: 20220626.1
2022-07-10T17:22:31.8351071Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220626.1/images/linux/Ubuntu2004-Readme.md
2022-07-10T17:22:31.8351692Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220626.1
2022-07-10T17:22:31.8352167Z ##[endgroup]
2022-07-10T17:22:31.8352461Z ##[group]Virtual Environment Provisioner
2022-07-10T17:22:31.8352811Z 1.0.0.0-main-20220616-1
2022-07-10T17:22:31.8353121Z ##[endgroup]
2022-07-10T17:22:31.8354019Z ##[group]GITHUB_TOKEN Permissions
2022-07-10T17:22:31.8354679Z Actions: write
2022-07-10T17:22:31.8355127Z Checks: write
2022-07-10T17:22:31.8355539Z Contents: write
2022-07-10T17:22:31.8355806Z Deployments: write
2022-07-10T17:22:31.8356115Z Discussions: write
2022-07-10T17:22:31.8356591Z Issues: write
2022-07-10T17:22:31.8356828Z Metadata: read
2022-07-10T17:22:31.8357182Z Packages: write
2022-07-10T17:22:31.8357870Z Pages: write
2022-07-10T17:22:31.8358147Z PullRequests: write
2022-07-10T17:22:31.8358735Z RepositoryProjects: write
2022-07-10T17:22:31.8359094Z SecurityEvents: write
2022-07-10T17:22:31.8359419Z Statuses: write
2022-07-10T17:22:31.8359741Z ##[endgroup]
2022-07-10T17:22:31.8363808Z Secret source: Actions
2022-07-10T17:22:31.8364247Z Prepare workflow directory
2022-07-10T17:22:31.9387928Z Prepare all required actions
2022-07-10T17:22:31.9626089Z Getting action download info
2022-07-10T17:22:32.2110071Z Download action repository 'docker/login-action@v1' (SHA:dd4fa0671be5250ee6f50aedf4cb05514abda2c7)
2022-07-10T17:22:33.4780972Z Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
2022-07-10T17:22:34.7851672Z ##[group]Run docker/login-action@v1
2022-07-10T17:22:34.7852044Z with:
2022-07-10T17:22:34.7852316Z   ecr: auto
2022-07-10T17:22:34.7852681Z   logout: true
2022-07-10T17:22:34.7852915Z ##[endgroup]
2022-07-10T17:22:35.1197953Z ##[error]Username and password required
2022-07-10T17:22:35.1442675Z Post job cleanup.
2022-07-10T17:22:35.3180573Z [command]/usr/bin/docker logout 
2022-07-10T17:22:35.5980108Z Removing login credentials for https://index.docker.io/v1/
2022-07-10T17:22:35.6280332Z Cleaning up orphan processes
