### ISSUE TITLE
Permission denied on saving json credentials

### ISSUE THREAD

**Issue by Poeschl** [docker/login-action#24]
### Behaviour
When my action login into my GitHub Container Registry, the login fails with following error:

![image](https://user-images.githubusercontent.com/5469257/97091889-93010380-163f-11eb-9aa7-d9face8e9b80.png)

#### Steps to reproduce this issue

1. Specify correct registry, username, password
2. Try to login
3. fail

#### Expected behaviour

The login should be successful.

#### Actual behaviour

Errors with code 1

### Configuration

* Repository URL (if public):  https://github.com/Poeschl/Hassio-Addons/blob/master/.github/workflows/master-push.yaml#L119
* Build URL (if public):  https://github.com/Poeschl/Hassio-Addons/runs/1302956818

```yml
  
name: Deploy addons
on:
  push:
    branches:
      - master

jobs:
  build-image:
    name: Build changed addons
    runs-on: ubuntu-latest

...

    steps:

...

      - name: Docker Login
        if: steps.files-check.outputs.changed == 'true'
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
...
```

### Logs

[log.txt](https://github.com/docker/login-action/files/5433665/log.txt)
