### ISSUE TITLE
Error logging into GitHub container registry 

### ISSUE THREAD

**Issue by joeyvanlierop** [docker/login-action#26]
### Behaviour
I was previously (~10 days ago) able to log into the GitHub container registry with no issues. All of the sudden I am getting this error message when trying to log in:
```
🔑 Logging into ghcr.io...
Error: Error response from daemon: Get https://ghcr.io/v2/: denied: denied
```

#### Steps to reproduce this issue

1. Create a PAT with the `delete:packages` and `write:packages` scopes
2. Add `CR_PAT` secret with the PAT
3. Run a workflow with the configuration mentioned below

#### Expected behaviour

I expect to be able to log into the GitHub container registry with no errors. The expected output it:
```
🔑 Logging into ghcr.io...
🎉 Login Succeeded!
```

### Configuration

The relevant section in the workflow file:
```
- name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
  registry: ghcr.io
  username: ${{ github.repository_owner }}
  password: ${{ secrets.CR_PAT }}
```

### Logs

Private repository with potentially sensitive information. If needed urgently, let me know and I will see what I can do.
