### ISSUE TITLE
Username and password not recognized

### ISSUE THREAD

**Issue by slimcdk** [docker/login-action#29]
### Behaviour
I'm using [this](https://github.com/docker/login-action#dockerhub) example to authenticate with docker hub, however the build fails with the error. What am I missing?
Secrets are set. Both username, password and a PAT - nothing fixes it

```bash
Run docker/login-action@v1
  with:
    logout: true
Error: Username and password required
```

Configuration
```yml
name: Publish Docker image
on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: <removed>:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```
