### ISSUE TITLE
Log on private registry (HTTP)

### ISSUE THREAD

**Issue by mmarcoux09** [docker/login-action#295]
#### Steps to reproduce this issue

1. Initiate the login-action
2. Pass a HTTP registry hostname
3. Error -> Error: Error response from daemon: Get "https://***/v2/": http: server gave HTTP response to HTTPS client

#### Expected behaviour

> Being able to login in a private registry even if not HTTPS

#### Actual behaviour

> Error: Error response from daemon: Get "https://***/v2/": http: server gave HTTP response to HTTPS client

### Configuration

* Repository URL (if public): https://github.com/mmarcoux09/nodejs-docker-template
* Build URL (if public): https://github.com/mmarcoux09/nodejs-docker-template/actions/runs/3191855463/jobs/5208656097

```yml
name: Build And Push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.NEXUS_HOST }}/app:latest
```

Thanks!
