### ISSUE TITLE
I get "Username and password required" even with an "if" condition on the step that evaluates to false...

### ISSUE THREAD

**Issue by rcdailey** [docker/login-action#305]
I'm using the below workflow (simplified):

```yml
env:
  SHOULD_PUBLISH: ${{ startsWith(github.ref, 'refs/tags/') || github.ref_name == 'master' }}

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        if: env.SHOULD_PUBLISH
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

When someone publishes a pull request from their fork, of course those two secrets will not be available. *However*, because I have the `if:` condition set up, in my mind, it should not matter if those variables are empty/undefined.

Unfortunately, though, I get this error:

> Error: Username and password required

See the error in my github workflow build result [here](https://github.com/recyclarr/recyclarr/actions/runs/3278481628/jobs/5396983124#step:8:8). You can see that `SHOULD_PUBLISH: false`.

So my question is: Why does this error happen if the `if:` condition won't allow this step to run anyway? I assume this is a github actions thing, and nothing you can change. If that's the case, can you propose a workaround for this? For example, would it work to do something like this?

```yml
with:
  username: ${{ secrets.DOCKERHUB_USERNAME || '' }}
  password: ${{ secrets.DOCKERHUB_TOKEN || '' }}
```

You can find the github workflow in my repo [here](https://github.com/recyclarr/recyclarr/blob/master/.github/workflows/docker.yml#L52-L57).
