### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by dnjs0718** [docker/login-action#306]
#### Steps to reproduce this issue

1. Use github action
2. Execute deploy yaml file
3. The warning Message happened

How can I solve it?
Do I need to upgrade? If yes, which version should I use?

#### Expected behaviour

> Tell us what should happen

The warning Message should not be shown

#### Actual behaviour

> Tell us what happens instead

The warning Message is shown to me

### Configuration

* Repository URL (if public): x
* Build URL (if public): x

```yml
- name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: companyname-harbor.duckdns.org
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. docker/login-action
```
