### ISSUE TITLE
Where is the config.json?

### ISSUE THREAD

**Issue by mgalgs** [docker/login-action#32]
I'm a little confused about how this action's side-effects are persisted. I expected to see a `$HOME/.docker/config.json` file but I'm not seeing it.

The problem I'm trying to solve is enabling experimental `docker` CLI features in a subsequent step after using `docker/login-action`. I'm trying:

    DOCKER_CFG_PATH="${DOCKER_CONFIG:-$HOME/.docker}/config.json"
    jq '. + {"experimental": "enabled"}' < "$DOCKER_CFG_PATH" | sponge "$DOCKER_CFG_PATH"

but `$DOCKER_CFG_PATH` doesn't exist. When I try to create an empty `config.json` and set the experimental flag on that I lose my `docker login` session.

Any tips on enabling experimental `docker` CLI features after using this action? Thanks!

**Comment by crazy-max** [comment]
@mgalgs 

> Any tips on enabling experimental docker CLI features after using this action? Thanks!

* https://github.com/actions/starter-workflows/issues/336
* https://github.com/actions/runner/issues/533

**Comment by mgalgs** [comment]
Thanks @crazy-max. Those issues are both the result of trying to write to `/etc/docker/daemon.json` as non-root. I'm actually not trying to write to `/etc/docker/daemon.json` (in fact, that file doesn't exist in my container).

I'm trying to figure out where `docker/login-action` stashes its credentials after logging in. It must be in the `GITHUB_WORKSPACE` somewhere, right? I've been digging through the source but I'm just not seeing it...

**Comment by crazy-max** [comment]
@mgalgs Config is located in `$HOME/.docker/config.json` or `$DOCKER_CONFIG`. Before/after login it's available for me:

```yaml
name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        run: |
          cat $HOME/.docker/config.json
      -
        name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        run: |
          cat $HOME/.docker/config.json
```

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "***"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.13+azure (linux)"
	}
}
```

What virtual environment are you using? Are you on a self-hosted runner?

**Comment by mgalgs** [comment]
gaaah I just realized what my issue was, thanks to your comment.

I was trying to access `~/.docker/config.json` from within my own custom action. So I was running in a docker container, not in the runner where `docker/login-action` does its work. That's why I couldn't see any `~/.docker/config.json` being created :facepalm: 

My `docker login` step is now _two_ steps, and looks like this:

```yaml
    - name: Login to DockerHub on runner
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to DockerHub on workspace
      uses: docker://docker
      with:
        entrypoint: docker
        args: login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password="${{ secrets.DOCKERHUB_TOKEN }}"
```

With that, I can build custom actions that use private image bases _and_ interact with the registry from _within_ my custom actions themselves.

I'll submit a patch with a small note on the README in case it's useful.

**Comment by crazy-max** [comment]
@mgalgs 

> To fix this, my docker login step is now two steps, and looks like this:

No need to repeat the login step in your DinD container as the host sock is already bind mounted (through `-v /var/run/docker.sock:/var/run/docker.sock`). See `Run docker://docker` logs in your action. You just need to specify the `DOCKER_CONFIG` env var in your job:

```yaml
name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      -
        name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        uses: docker://docker
        with:
          entrypoint: docker
          args: info
```

The output of `docker info` then shows you are actually logged in (`Username: ***`):

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 19.03.13+azure
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1031-azure
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.791GiB
 Name: fv-az195-229
 ID: IXQT:L7LF:S2BO:GSCG:RPGQ:P7JE:3WUH:JNHZ:4WSJ:YOUR:ZMBB:PQRV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ***
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

> I'll submit a patch with a small note on the README in case it's useful.

Thank you, but for me I don't think we wish to endorse this kind of use case for this action.
WDYT @justincormack @tonistiigi @chris-crone?
