### ISSUE TITLE
Docker login returns 503

### ISSUE THREAD

**Issue by asad-awadia** [docker/login-action#328]
### Behaviour

Docker login returns 503 for a self hosted registry. I have confirmed that the registry is NOT down. I can go to `https://registry.xyz.dev/v2/<name>/tags/list` and see the response in my browser as well as push/pull/login from local

Registry is deployed as a docker container on a regular VPS with nginx in front of it

Cloudflare is used for DNS

Docker login works from local mac [on wifi and mobile data [to verify firewall issues] ] - it also works from the VPS it self

I am not seeing logs on nginx or the registry containers for the login request for some reason

#### Expected behaviour

Docker login should succeed

#### Actual behaviour

Docker login returns 503

### Configuration

```yml
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.xyz.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
```

### Logs

```
Error response from daemon: login attempt to https://registry.xyz.dev/v2/ failed with status: 503 Service Unavailable
```

Registry configuration is as following

```
  registry:
    image: registry:2.8.1
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_HOST: "https://registry.xyz.dev"
    volumes:
      - ./registry/registry.password:/auth/registry.password
      - ./registry/data:/data
    ports:
      - 5000
```

Nginx uses Certs from cloudflare and forwards the request to the registry - am I missing something? Why is it 503?

I tried searching - but can't find anything related to a 503 on docker login
