### ISSUE TITLE
Error when job triggered by `workflow_call`

### ISSUE THREAD

**Issue by lkurija2** [docker/login-action#390]
### Behaviour
When a login action (child workflow) is called by referencing it through a parent workflow file, the login will fail with the following error message - `Error: Username and password required`
#### Steps to reproduce this issue

1. Create a file `child-login.yaml` and add the login job with the `on: workflow_call`
```yaml
name: Login test

on: workflow_call

jobs:
  perform-login:
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: <location>-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GAR_KEY_B64 }}

```
2. Create a file called `parent-workflow.yaml` and add the reference of the child job as the job
```yaml
name: Parent workflow test

on:
  - push

jobs:
  login:
    uses: ./.github/workflows/child-login.yaml

```
3. Trigger the `Parent workflow test`

#### Expected behaviour

Docker is logged in successfully.

#### Actual behaviour

An error occurs
> Error: Username and password required
![image](https://user-images.githubusercontent.com/88312505/214978619-23e677a1-1915-4df3-a761-3d6e5b1e5eef.png)

### Configuration

* Repository URL (if public): /
* Build URL (if public): /

### Logs

```txt
2023-01-26T23:42:33.6246986Z ##[group]Run docker/login-action@v2
2023-01-26T23:42:33.6247311Z with:
2023-01-26T23:42:33.6247580Z   registry: XXXXXXXXXX-docker.pkg.dev
2023-01-26T23:42:33.6247889Z   username: _json_key_base64
2023-01-26T23:42:33.6248142Z   ecr: auto
2023-01-26T23:42:33.6248366Z   logout: true
2023-01-26T23:42:33.6248583Z ##[endgroup]
2023-01-26T23:42:33.7890370Z ##[error]Username and password required
```
