### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by enahsor** [docker/login-action#417]
### Behaviour

This might be a temporary issue that is entirely on github's side but on the off chance that it is being caused by this action, I'm posting here. (If it is ever resolved without any action from any of the authors or myself, I will close this issue myself.)

#### Expected behaviour

I expected docker to authenticate to artifact registry using the variables I provided

#### Actual behaviour

I ended receiving this error:
`Error response from daemon: Get "https://us-central1/v2/": dial tcp: lookup us-central1: Temporary failure in name resolution
` 

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Service CD

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: project-id
  LOCATION: us-central1
  REPO: repo-name
  SERVICE: service

jobs:
  upload-image-to-artifact-registry:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.LOCATION }}"

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{env.SERVICE}}:{{ github.sha }}" --build-arg BUILD_CONTEXT="{{ env.SERVICE }}" -f Dockerfile.prod ./
          docker push "${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{env.SERVICE}}:{{ github.sha }}"
  deploy-image:
    needs: upload-image-to-artifact-registry
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Authentication
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.LOCATION }}
          image: ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
