### ISSUE TITLE
Push only latest tag

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [docker/login-action#440]
### Behaviour
I would like to push to docker the current tag not the "latest" name tag when a new release is done.

#### Steps to reproduce this issue
I have this github action:
```
publish_docker_images:
    needs: [update-version]
    runs-on: ubuntu-20.04
       
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: phparkitect/arkitect-github-actions
        tags: |
          type=raw,value=latest,enable=${{ endsWith(github.ref, 'main') }}
          type=ref,event=tag
        flavor: |
          latest=false
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```

#### Expected behaviour

I would like to see the actual tag in docker hub

#### Actual behaviour

In docker hub I can see only the "latest" tag

### Configuration

* Repository URL (if public): https://github.com/phparkitect/arkitect-github-actions
* Build URL (if public): https://github.com/phparkitect/arkitect-github-actions/blob/main/.github/workflows/update_version.yml

```yml
publish_docker_images:
    needs: [update-version]
    runs-on: ubuntu-20.04
       
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: phparkitect/arkitect-github-actions
        tags: |
          type=raw,value=latest,enable=${{ endsWith(github.ref, 'main') }}
          type=ref,event=tag
        flavor: |
          latest=false
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```
