### ISSUE TITLE
Cannot login with self-host registry

### ISSUE THREAD

**Issue by nvti** [docker/login-action#461]
### Behaviour
I hosted a registry and used Cloudflare as DNS and served SSL. I can log in to my registry by using terminal with `docker login` command. But when I use github action to login, I got error: `Error response from daemon: login attempt to https://***/v2/ failed with status: 403 Forbidden`

#### Steps to reproduce this issue

1. Selfhost registry with htpasswd auth
2. Setup github action:
```yaml
steps:
  - uses: actions/checkout@v3
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      registry: ${{ secrets.REGISTRY_DOMAIN }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
```

#### Expected behaviour
Login success

#### Actual behaviour
Got error: Error response from daemon: login attempt to https://***/v2/ failed with status: 403 Forbidden

> Tell us what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yaml
steps:
  - uses: actions/checkout@v3
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      registry: ${{ secrets.REGISTRY_DOMAIN }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
```
