### ISSUE TITLE
Login in Windows environment

### ISSUE THREAD

**Issue by nao20010128nao** [docker/login-action#47]
#### Steps to reproduce this issue

Run following workflow: (this is minimal I think)

```yaml
jobs:
  docker-windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DHUB_TOKEN }}
```

#### Expected behaviour

Login is performed. Whether it success or not.

#### Actual behaviour

Gives:

```yaml
Error: Only supported on linux platform
```

### Configuration

* Repository URL (if public): https://github.com/nao20010128nao/ytdl-patched
* Build URL (if public): https://github.com/nao20010128nao/ytdl-patched/runs/1586935526

https://github.com/nao20010128nao/ytdl-patched/blob/master/.github/workflows/build.yml

### Logs

[a.log](https://github.com/docker/login-action/files/5722326/a.log)
