### ISSUE TITLE
Logout parameter and interaction with other docker actions

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [docker/login-action#51]
Hello,

I'd like to further understand how `docker/login-action` interacts with other `docker` actions like `docker/build-push`, and the VM in general. To keep it simple: is the purpose of this action to login the user on the `runs-on` VM? Then, whatever actions require being logged in come after like `build-push`? 

This is my initial understanding, although finding the `logout` parameter has me questioning that understanding. As far as I understand, having `post: 'dist/index.js'` in `action.yml` runs the `logout` function in `src/docker.ts`, which is really just the `docker logout <registry>` shell command. This is ran, I think, once the `main:` command finishes executing, and before the next job. But if that is correct, then the following would happen using `login-action` with `logout: true`, and then using `build-push`:

* login
* logout
* build
* push

That doesn't make sense, so I must be misunderstanding the sequence here. Do `post` actions happen at a different time than I expect, or is it something else? Any clarification would be appreciated.

**Comment by crazy-max** [comment]
@AnthonyMonterrosa  

> This is ran, I think, once the `main:` command finishes executing,

Actually no, `post` will run when **all main** of the job are completed, not the action itself is completed.

For example this workflow:

```yaml
name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v2
```

Will have the following execution timeline:

* `actions/checkout` run
* `docker/setup-buildx-action` run
* `docker/login-action` run
* `docker/build-push-action` run
* `docker/login-action` post
* `docker/setup-buildx-action` post
* `actions/checkout` post

See https://github.com/crazy-max/diun/runs/1678401960?check_suite_focus=true
