### ISSUE TITLE
Error getting credentials and error saving credentials

### ISSUE THREAD

**Issue by C0depark** [docker/login-action#515]
### Behaviour
Something breaks with Docker after deleting and re-building containers multiple times and I can no longer get or store credentials. The only workaround I found was to completely uninstall Docker, restart the computer, and re-install. Clean/purging data and resetting to factory defaults does not fix..

```
error getting credentials - err: exit status 1, out: ``
```
```
Error saving credentials: error storing credentials - err: exit status 1, out: ``
```

Docker version 23.0.5, build bc4487a.
Running in WSL2 - Ubuntu 22.04.2 LTS, Windows 11 Pro
Diagnositcs ID: 85DE5AC6-CC52-46D6-8150-6DCC0B3759F0/20230524132659

#### Steps to reproduce this issue

1. Run docker login command with a github token
2. Build containers, preferably with an image sourced from docker.pkg.github.com 
3. Run the containers
4. Delete and rebuild the containers a few times

#### Expected behaviour

> Login should be remembered and containers should rebuild without issue

#### Actual behaviour

> I receive the following error:
error getting credentials - err: exit status 1, out: ``

> When attempting to run docker login again, I receive this error:
Error saving credentials: error storing credentials - err: exit status 1, out: ``

### Configuration

* Repository URL (if public): Not public
* Build URL (if public): Not public

```yml
version: '3.1'
services:
  mongodb:
    container_name: 'mongodb'
    image: 'mongo:4.0'
    ports:
      - '27017'
    restart: 'on-failure'
  mariadb:
    container_name: 'mariadb'
    image: 'docker.pkg.github.com/private-source/mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306'
    restart: 'on-failure'
  solr:
    container_name: 'solr'
    image: 'docker.pkg.github.com/private-source/solr:latest'
    ports:
      - '8983'
  app:
    container_name: 'app'
    image: ###built from dockerfile###
    environment:
      MARIADB_HOST: 'mariadb'
      MEDIA_API_BASE_URL: 'http://api'
      MONGODB_HOST: 'mongodb://mongodb'
      SOLR_HOST: 'solr'
      TZ: 'America/New_York'
    volumes:
      - ./application:/app/latest/application
      - ./library:/app/latest/library
      - ./public:/app/latest/public
      - ./tests:/app/latest/tests
      - ./vendor:/app/latest/vendor
    ports:
      - '80'
    restart: 'on-failure'
  api:
    container_name: 'api'
    image: 'docker.pkg.github.com/private-source/api:latest'
    environment:
      MONGODB_HOST: 'mongodb://mongodb'
      TZ: 'America/New_York'
    ports:
      - '80'
    restart: 'on-failure'

```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
N/A - Local build
