### ISSUE TITLE
Support multi-user login

### ISSUE THREAD

**Issue by a76yyyy** [docker/login-action#516]
### Behaviour

Currently it seems to support only a single user login to a hub address, hope to support multi-user login

#### Steps to reproduce this issue

```yaml
- name: a Login to DockerHub
  uses: docker/login-action@v2
  with:
    registry: docker.io
    username: ${{ secrets.A_DOCKER_USERNAME }}
    password: ${{ secrets.A_DOCKER_PASSWORD }}
- name: b login to DockerHub
  uses: docker/login-action@v2
  with:
    registry: docker.io
    username: ${{ secrets.b_DOCKER_USERNAME }}
    password: ${{ secrets.b_DOCKER_PASSWORD }}
```

#### Expected behaviour

Support multi-user login

```json
# cat ~/.docker/config.json

{
    "auths":{
        "https://index.docker.io/v1/":{
            "auth":"xxxx"
        },
        "https://index.docker.io/v1/":{
            "auth":"xxxx"
        }
    }
}
```

#### Actual behaviour

```json
# cat ~/.docker/config.json

{
    "auths":{
        "https://index.docker.io/v1/":{
            "auth":"xxxx"
        }
    }
}
```
