### ISSUE TITLE
Login fails asking for a password although one appears to be provided

### ISSUE THREAD

**Issue by AlexJeffcott** [docker/login-action#52]
### Behaviour

When running workflow it errors at the login step, talking about a missing password.

I have created a PAT as described in https://github.com/docker/login-action/issues/6

#### Steps to reproduce this issue

1. run workflow

#### Expected behaviour

> Should log in as expected

#### Actual behaviour

> Errors
![image](https://user-images.githubusercontent.com/9036846/105525380-4fbb3d00-5ce1-11eb-8b58-b4216e3237ba.png)

### Configuration

* https://github.com/AlexJeffcott/amboss-cypress-demo
* https://github.com/AlexJeffcott/amboss-cypress-demo/runs/1750353837?check_suite_focus=true

```yml
name: Deploy and run

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
```

### Logs

> https://github.com/AlexJeffcott/amboss-cypress-demo/runs/1750353837?check_suite_focus=true#step:3:6
