### ISSUE TITLE
Feature request: Insecure registry

### ISSUE THREAD

**Issue by danbalarin** [docker/login-action#53]
Hi, it would be nice to add support for registries served only over http instead of https. Right now it gives this error: 
```
Error response from daemon: Get https://***/v2/: http: server gave HTTP response to HTTPS client
```

**Comment by crazy-max** [comment]
@danbalarin If you try to login to an insecure registry, [it’s not possible with basic authentication.](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry).

If you want to pull or push an image you can set your registry as insecure in a step before:

```yaml
name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set insecure registry
        run: |
          echo "{ \"insecure-registries\": [\"${{ secrets.DOCKER_REGISTRY }}\"] }" | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      -
        name: Pull
        run: |
          docker pull ${{ secrets.DOCKER_REGISTRY }}/myimage:latest
```

But again **this is very insecure and is not recommended.**

**Comment by crazy-max** [comment]
If you're using a [local registry in your workflow for testing purposes](https://github.com/docker/build-push-action/#local-registry) you can use the [build push action](https://github.com/docker/build-push-action) and do that instead:

```yaml
name: ci

on:
  push:
    branches: master

jobs:
  local-registry:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/name/app:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest
```
