### ISSUE TITLE
Logging in to Github Container Registry

### ISSUE THREAD

**Issue by rfftrifork** [docker/login-action#54]
### Behaviour

```
Run docker/login-action@v1
Error: Username and password required
```

#### Steps to reproduce this issue

1. Follow your guide here: https://github.com/docker/login-action#github-container-registry

#### Expected behaviour

It should at least log in. I assume that the token I created should be added to the secrets (will try that in a moment)

Also project wide settings should not depend on personal tokens. IMO it's a an obviously bad design. The token is personal, the user might accidentally delete it, leave the projects etc. Either it should dynamically identify as committing user, or it should identify as the pipeline. It should not require the project to contain personal tokens in shared configs.

#### Actual behaviour

Isn't this the same as behaviour?

### Configuration

* Repository URL (if public): N/A (not public)
* Build URL (if public): N/A (not public)

The part that fails:

```yml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
