### ISSUE TITLE
Usage with registry.hop.io

### ISSUE THREAD

**Issue by PiWizard3852** [docker/login-action#554]
I would like to push my docker image to the hop.io registry (registry.hop.io) in my GitHub Action. This is what my worflow.yml file looks like: 

```YAML
name: Wayve CI

on:
  push:
    branches: [ 'main' ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: registry.hop.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Wayve
        uses: actions/checkout@v3

      - name: Get Email
        id: userEmail
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.actor }}

      - name: Log in to the Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.userEmail.outputs.email }}
          password: ${{ secrets.HOP_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

When pushing from the command line, the cli prompts for a username (which is the accounts email) and a password (which is the accounts personal access token). When I committed this, I got the following error: 
`Error: buildx failed with: ERROR: unauthorized: authentication required`

Does someone know how to use docker/login-action with the hop.io registry?
