### ISSUE TITLE
Unable to locate executable file: aws

### ISSUE THREAD

**Issue by frndmg** [docker/login-action#56]
#### Steps to reproduce this issue

1. Run the CI with the steps described in the Configuration section.

#### Expected behaviour

It should login to AWS Elastic Container Registry

#### Actual behaviour

The executable `aws` is missing.

### Configuration

```yml
name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:

  push_to_registry:

    name: Push Docker image to GitHub Packages

    runs-on: [***]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/***,***.dkr.ecr.***.amazonaws.com/***
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ***

      - uses: docker/login-action@v1
        with:
          registry: ***.dkr.ecr.***.amazonaws.com

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: |
            token=${{ secrets.PERSONAL_GITHUB_TOKEN }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
```

### Logs

[1_Push Docker image to GitHub Packages.txt](https://github.com/docker/login-action/files/6084530/1_Push.Docker.image.to.GitHub.Packages.txt)
