### ISSUE TITLE
Harbor login issue: authentication required

### ISSUE THREAD

**Issue by enzofoucaud** [docker/login-action#584]
#### Expected behaviour

> Login to [Harbor](https://goharbor.io/)

#### Actual behaviour

> error: unauthorized: authentication required

![image](https://github.com/docker/login-action/assets/15039645/d17f2801-b70d-47f1-a456-0066011dc4ef)

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker XXX
        uses: docker/login-action@v2
        with:
          registry: docker.XXX.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

### Logs

> Gitea action CLI
```
Logging into docker.XXX.com...
::error::Error response from daemon: Get "https://docker.XXX.com/v2/": unauthorized: authentication required
```

> Gitea runner logs
```
gitea_runner1   | [Gitea Actions Demo/docker] ⭐ Run Main Login to Docker XXX
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing entry to tarball workflow/outputcmd.txt len:0
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing entry to tarball workflow/statecmd.txt len:0
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing entry to tarball workflow/pathcmd.txt len:0
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing entry to tarball workflow/envs.txt len:0
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing entry to tarball workflow/SUMMARY.md len:0
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Extracting content to '/var/run/act'
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] About to run action &{Docker Login docker GitHub Action to login against a Docker registry map[ecr:{Specifies whether the given registry is ECR (auto, true or false) false auto} logout:{Log out from the Docker registry at the end of a job false true} password:{Password or personal access token used to log against the Docker registry false } registry:{Server address of Docker registry. If not set then will default to Docker Hub false } username:{Username used to log against the Docker registry false }] map[] {node16 map[] dist/index.js  always() dist/index.js always()   [] []} {blue anchor}}
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] type=remote-action actionDir=/root/.cache/act/docker-login-action@master actionPath= workdir=/workspace/sandbox/test_gitea_action actionCacheDir=/root/.cache/act actionName=docker-login-action@master containerActionDir=/var/run/act/actions/docker-login-action@master
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Removing /root/.cache/act/docker-login-action@master/.gitignore before docker cp
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] /var/run/act/actions/docker-login-action@master
gitea_runner1   | [Gitea Actions Demo/docker]   🐳  docker cp src=/root/.cache/act/docker-login-action@master/ dst=/var/run/act/actions/docker-login-action@master/
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Writing tarball /tmp/act26568936 from /root/.cache/act/docker-login-action@master/
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Stripping prefix:/root/.cache/act/docker-login-action@master/ src:/root/.cache/act/docker-login-action@master/
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Extracting content from '/tmp/act26568936' to '/var/run/act/actions/docker-login-action@master/'
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] executing remote job container: [node /var/run/act/actions/docker-login-action@master/dist/index.js]
gitea_runner1   | [Gitea Actions Demo/docker]   🐳  docker exec cmd=[node /var/run/act/actions/docker-login-action@master/dist/index.js] user= workdir=
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Exec command '[node /var/run/act/actions/docker-login-action@master/dist/index.js]'
gitea_runner1   | [Gitea Actions Demo/docker] [DEBUG] Working directory '/workspace/sandbox/test_gitea_action'
gitea_runner1   | [Gitea Actions Demo/docker]   | Logging into docker.XXX.com...
gitea_runner1   | [Gitea Actions Demo/docker]   💬  ::debug::Exec.getExecOutput: docker login --password-stdin --username *** docker.XXX.com
gitea_runner1   | [Gitea Actions Demo/docker]   | ::debug::Exec.getExecOutput: docker login --password-stdin --username *** docker.XXX.com
gitea_runner1   | [Gitea Actions Demo/docker]   ❗  ::error::Error response from daemon: Get "https://docker.XXX.com/v2/": unauthorized: authentication required
gitea_runner1   | [Gitea Actions Demo/docker]   | ::error::Error response from daemon: Get "https://docker.XXX.com/v2/": unauthorized: authentication required
gitea_runner1   | [Gitea Actions Demo/docker]   ❌  Failure - Main Login to Docker XXX
gitea_runner1   | [Gitea Actions Demo/docker] exitcode '1': failure
```
