### ISSUE TITLE
Failure to publish an anonymous docker container

### ISSUE THREAD

**Issue by bsergean** [docker/login-action#6]
Hi there,

I'm trying to setup something for an open-source library hosted on my company space. I am getting an [error](https://github.com/machinezone/IXWebSocket/runs/1063249282?check_suite_focus=true) though when my action runs at the login step, talking about a missing password.

```
 Login to GitHub Package Registry
0s
    logout: true
Run docker/login-action@v1
  with:
    registry: ghcr.io
    username: machinezone
    logout: true
##[error]Input required and not supplied: password
```

I used this, hoping that the secret would be populated, following this [blog post](https://www.docker.com/blog/docker-support-for-the-new-github-container-registry/).

```
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
```

The full yaml for the github action is [here](https://github.com/machinezone/IXWebSocket/blob/master/.github/workflows/docker.yml).

Any clue on what might be going on ?
Should I report that on the github login action instead maybe ... ?

**Comment by crazy-max** [comment]
@bsergean You have to create a GitHub PAT as explained in the [README](https://github.com/docker/login-action#github-container-registry). Have been tested [here](https://github.com/crazy-max/docker-login-action/blob/test/.github/workflows/ci.yml#L53-L59):

![image](https://user-images.githubusercontent.com/1951866/92184020-7c101300-ee3f-11ea-9b07-381fa3a36bd9.png)
> https://github.com/crazy-max/docker-login-action/runs/1069446285?check_suite_focus=true#step:3:8

**Comment by bsergean** [comment]
Thank you.

**Comment by dryleaf** [comment]
I have added the action on my workflow:
```
- name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
    registry: ghcr.io
    username: ${{ github.repository_owner }}
    password: ${{ secrets.CR_PAT }}
```
- The `secrets.CR_PAT` is configured and works normally on my local environment.

I get the following error:
```
Run docker/login-action@v1
  with:
    registry: ghcr.io
    username: dryleaf
    logout: true
  env:
    IMAGE_NAME: oauth
Error: Username and password required
```

I can't seem to find the issue
