### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by 0n1dev** [docker/login-action#613]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I am using a Docker private registry, but I am encountering TLS-related errors when attempting to perform 'docker login'."

### Expected behaviour

Successful Docker login.

### Actual behaviour

Error response from daemon: Get "[https://registry.***.io/v2/](https://registry.%2A%2A%2A.io/v2/)": tls: failed to verify certificate: x509: certificate signed by unknown authority

### YAML workflow

```yaml
docker-build:
    needs: jar-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs
    - name: Set ENV
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: registry.akaiv.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      id: docker_build
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          registry.akaiv.io/${{ github.event.repository.name }}:latest
          registry.akaiv.io/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}
```

### Workflow logs

Error response from daemon: Get "[https://registry.***.io/v2/](https://registry.%2A%2A%2A.io/v2/)": tls: failed to verify certificate: x509: certificate signed by unknown authority
