### ISSUE TITLE
Error: unknown flag: --password-stdin

### ISSUE THREAD

**Issue by ticteam** [docker/login-action#62]
#### Steps to reproduce this issue

1. create secrets: REGISTRY_USER_NAME & REGISTRY_USER_PSW
2.  run the manual.yaml from ### Configuration
3. tried with and with out "with: registry: docker.io"

#### Expected behaviour

successfully login to docker hub && push image to docker hub

#### Actual behaviour
from log: 

```
Run docker/login-action@v1.8.0
  with:
    username: ***
    password: ***
    logout: true
🔑 Logging into Docker Hub...
Error: unknown flag: --password-stdin
```

### Configuration

```yaml
name: Manual workflow
on: push
jobs:
  build_image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build Docker image
      env: 
        REGISTRY_USER_NAME: ${{ secrets.REGISTRY_USER_NAME }}
        REGISTRY_USER_PSW: ${{ secrets.REGISTRY_USER_PSW }}    
      run: |
        ls -la && \
        docker build -t docker.io/ticteam/feedback .
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.REGISTRY_USER_NAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_USER_PSW }}
        
    - name: push image to DockerHub
      run: |
        docker push docker.io/ticteam/feedback
```

### Logs

[logs_13.zip](https://github.com/docker/login-action/files/6259026/logs_13.zip)

**Comment by crazy-max** [comment]
@ticteam 

> `runs-on: self-hosted`

Looks like you are on self-hosted runner. And looking at the error, I suspect you are on a pretty old version of Docker (~17.07).
Can you add those steps after checkout please?:

```yaml
     - name: Docker info
       run: docker info
     - name: Docker version
       run: docker version
```
