### ISSUE TITLE
Login is not able to get GitHub Actions secrects.

### ISSUE THREAD

**Issue by ArielLahiany** [docker/login-action#67]
#### Expected behavior

> Login into DockerHub.

#### Actual behaviour

> The system throws an error: "Error: Username and password required".

### Configuration

* Repository URL (if public): https://github.com/ArielLahiany/marionette/
* Build URL (if public): 

```yml
name: Docker Publish

on:
  push:
    branches:
      - master


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

```
[logs_19.zip](https://github.com/docker/login-action/files/6478373/logs_19.zip)
