### ISSUE TITLE
login-action step fails in Github pull request checks

### ISSUE THREAD

**Issue by Tsingis** [docker/login-action#686]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

login-action@v3 appears to randomly fail in Github pull request checks.

### Expected behaviour

Login to succeed with given username and token.

```
Run docker/login-action@v3
Logging into Docker Hub...
Login Succeeded!
```

### Actual behaviour

Login with username and token fails giving error message _"Error: Username and password required"_
```
Run docker/login-action@v3
  with:
    logout: true
    ecr: auto
Error: Username and password required
```

### Repository URL

https://github.com/Tsingis/bitcoin-web-api

### Workflow run URL

https://github.com/Tsingis/bitcoin-web-api/actions/runs/8269281351/job/22624187939

### YAML workflow

```yaml
name: build-docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
```

### Workflow logs

```
Run docker/login-action@v3
  with:
    logout: true
    ecr: auto
Error: Username and password required
```
