### ISSUE TITLE
Support for azure/login@v2?

### ISSUE THREAD

**Issue by andrasg** [docker/login-action#700]
### Description

I am trying to push to an Azure Container Registry using `azure/login@v2`.

I have successfully setup federated workload identities auth using: [Configure a federated identity credential on an app](https://learn.microsoft.com/entra/workload-id/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions)

```yaml
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

The above task successfully authenticates to Azure. I am unsure though how `docker/login-action@v3` would be able to pick up the authenticated context. Is this supported? If not, would be a great addition.

nb: auth to ACR using username+password works great:

```yaml
      - name: 'Docker login'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
```
