### ISSUE TITLE
Custom ENV DOCKER_CONFIG value request.

### ISSUE THREAD

**Issue by SimonSQLML** [docker/login-action#734]
### Description

https://github.com/docker/login-action/blob/0d4c9c5ea7693da7b068278f7b52bda2a190a446/.github/workflows/ci.yml#L59C7-L59C35

$HOME/.docker is hardcoaded.

https://github.com/docker/login-action/blob/0d4c9c5ea7693da7b068278f7b52bda2a190a446/src/main.ts file doesn't care the env Docker_config path.

large in-house build server has multiple github agents running.
Each agent update and cleanup the same file under $HOME/.docker/config.json file.

it causes randomly authentrication failure for private registry.

We don't want to use logout: true part. It is security concern.

#173 
There is similar issue.
However, the env option doesn't work in the below.

```
- name: Set DOCKER_CONFIG
  run: |
    mkdir -p $HOME/${{ env.GITHUB_RUN_ID }}/.docker
    echo "DOCKER_CONFIG=$HOME/${{ env.GITHUB_RUN_ID }}/.docker" >> $GITHUB_ENV

- name: Login build and test machine to myreg.azurecr.io
  uses: docker/login-action@v1
  with:
    registry: myreg.azurecr.io
    username: myreg
    password: ${{ secrets.AZURECR_PASSWORD }}
```
