### ISSUE TITLE
libc issue on ubuntu-latest (22.04)

### ISSUE THREAD

**Issue by gussmith23** [docker/login-action#745]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The correct libc isn't being found. Unclear to me where within this action this error is being triggered.

This started happening w/o any changes on my side. I tried updating from v2->v3.2.0, but no change.

Thanks all for the action, by the way!

### Expected behaviour

No error.

### Actual behaviour

Instead, I see the following:
```
Run docker/login-action@v3.2.0
  with:
    registry: ghcr.io
    username: gussmith[2](https://github.com/uwsampl/lakeroad/actions/runs/9784255189/job/27014840789#step:2:2)3
    password: ***
    ecr: auto
    logout: true
  env:
    REGISTRY: ghcr.io
    IMAGE_TAG: ghcr.io/uwsampl/lakeroad:sha-b[3](https://github.com/uwsampl/lakeroad/actions/runs/9784255189/job/27014840789#step:2:3)ed0e5d2abdca7fa4e9ccc32638d3cdeee9029d
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib6[4](https://github.com/uwsampl/lakeroad/actions/runs/9784255189/job/27014840789#step:2:4)/libm.so.6: version `GLIBC_2.27' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
/home/gus/github-actions-runners/lakeroad/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.2[5](https://github.com/uwsampl/lakeroad/actions/runs/9784255189/job/27014840789#step:2:5)' not found (required by /home/gus/github-actions-runners/lakeroad/externals/node20/bin/node)
```

### Repository URL

https://github.com/uwsampl/lakeroad

### Workflow run URL

https://github.com/uwsampl/lakeroad/actions/runs/9784255189/job/27014840789

### YAML workflow

```yaml
name: Run checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Run at 4am PT each day.
  schedule:
    - cron: "0 11 * * *"

  # Allow manual trigger.
  workflow_dispatch:
    inputs:
      no-cache:
        type: boolean
        description: use --no-cache flag on docker build. 'true' turns on --no-cache.

env:
  REGISTRY: ghcr.io
  # Can't use ${{ env.REGISTRY }} here, but would like to, so that we' don't
  # repeat ghcr.io.
  IMAGE_TAG: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
  
concurrency:
  # Cancel in-progress runs for branches other than main.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Job which cleans up GitHub Actions workspace. This is only needed when
  # running on self-hosted runners.
  #
  # TODO(@gussmith23) It would be nice if this wasn't necessary. We could use
  # this: https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job
  cleaner:
    runs-on: self-hosted
    steps:
      - name: Clean up previous runs
        run: rm -rf "${{ github.workspace }}"

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Set up SSH agent for cloning lakeroad-private.
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LAKEROAD_PRIVATE_SSH_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # If we want to do this more cleanly, we can use metadata-action.
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
          no-cache: ${{ github.event.inputs.no-cache == 'true' }}

  # This can be run on ubuntu-latest (i.e., on GitHub's provided runners), but
  # it will be much slower. Specifically, our end-to-end tests using Verilator
  # take advantage of the many threads on our machines, whereas the GitHub
  # machines only have two threads.
  #
  # Perhaps we should run this on both?
  run-tests:
    runs-on: self-hosted
    needs: [build-and-push-image, cleaner]
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_TAG }}

      - name: Run tests
        run: docker run ${{ env.IMAGE_TAG }} bash run-tests.sh

  check-format:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_TAG }}

      - name: Format check
        run: |
          docker run ${{ env.IMAGE_TAG }} \
            bash -c './fmt.sh && git diff && [ -z "$(git status --porcelain)" ]'
```
```


### Workflow logs

see above.

### BuildKit logs

_No response_

### Additional info

_No response_
