### ISSUE TITLE
Add retry

### ISSUE THREAD

**Issue by sophiewigmore** [docker/login-action#750]
Hey! Occasionally, our login step fails due to rate-limiting or the system we're logging into being unavailable. It would be super useful to have a retry flag of some kind.  Based on similar functionality for other actions in the space, imagining it might look like:
```
- name: Login
   uses: docker/login-action@v3
   with:
       registry: ...
       username: ...
       password: ...
       retry-attempts: 3
```
