### ISSUE TITLE
Username and password required

### ISSUE THREAD

**Issue by DoLoop216** [docker/login-action#772]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

I have been using this action for 900+ builds on this repo, and today, for some unknown reason, it started giving this error.

It simply says:
```
Run docker/login-action@v3
  with:
    registry: https://index.docker.io/v1/
    ecr: auto
    logout: true
Error: Username and password required
```

I haven't changed anything at all inside repo. Came back from few days vacation and let the build run with 1 line code change (not related to repo)
![image](https://github.com/user-attachments/assets/593193d7-947d-4ff4-9e72-12b9c534a9a6)
![image](https://github.com/user-attachments/assets/b9b9d86a-5d58-45de-8847-ba11fc363c76)

### Expected behaviour

For action to successfully login

### Actual behaviour

Drops error: "Error: Username and password required"

### YAML workflow

```yaml
name: Build and push termodom-office-public-api application docker image, then start deploying action

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    
jobs:
  build-and-push-termodom-office-public-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: docker build --file src/TD.Office/TD.Office.Public/TD.Office.Public.Api/Dockerfile -t limitlesssoft/termodom-office-public-api:${{ inputs.env }} .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push docker image
      run: docker push limitlesssoft/termodom-office-public-api:${{ inputs.env }}
      
  deploy:
    uses: limitlesssoft/termodom--ecosystem/.github/workflows/deploy-termodom-office-public-api.yml@master
    needs: [ build-and-push-termodom-office-public-api ]
    secrets: inherit
    with:
      env: ${{ inputs.env }}
```
