### ISSUE TITLE
Login credentials not found in subsequent steps

### ISSUE THREAD

**Issue by AAriam** [docker/login-action#822]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

My workflow builds and pushes a docker image using [RepoDynamics/BinderDocker@v0.1](https://github.com/RepoDynamics/BinderDocker), and adds an attestation using [actions/attest-build-provenance@v2](https://github.com/actions/attest-build-provenance) after pushing. I am trying to use `docker/login-action@v3` for logging in to ghcr.io once in the workflow job, so there is no need to login multiple times. Somehow, this does not work, and with all tested workflows, there is always the need to login twice. See Additional info section below for more details.

### Expected behaviour

The credentials must persist until the end of all steps.

### Actual behaviour

The credentials cannot be found on one of the subsequent steps.

### Repository URL

https://github.com/AAriam/docker-login-test

### Workflow run URL

https://github.com/AAriam/docker-login-test/actions/runs/12218303920

### Additional info

`BinderDocker` has the option to do the login itself, or you can log in in an earlier step. It also has the option to run `docker logout` at the end. But somehow even when I don't logout, `attest-build-provenance` raises the error `No credentials found for registry ghcr.io`. So I want to use `login-action`, then `BinderDocker` with no login, and then `attest-build-provenance` with no login, but the workflow only works if I login twice.

I created a [test repository](https://github.com/AAriam/docker-login-test) containing a [workflow](https://github.com/AAriam/docker-login-test/actions/runs/12218303920) to test different configurations. The matrix has the following variables:
- `env`: Whether to add `DOCKER_CONFIG: $HOME/.docker` to `jobs.<job-id>.env` as discussed in #32, #34, and #147.
- `first-login`: Whether to use `docker/login-action`, `repodynamics/binderdocker`, or both to login before pushing.
- `logout`: Whether to `docker logout` at the end of pushing.
- `second-login`: Whether to use `docker/login-action` to log in after pushing and before attestation.

Here are the results; in summary, it only works when `DOCKER_CONFIG: $HOME/.docker` is **not added** and login is performed at least twice:

| Status | `env` | `first-login` | `logout` | `second-login` | Failing Action |
| ------ | --- | ----------- | ------ | ------------ | ----- |
| ✅ | no | both | no | no | -
| ✅ | no | both | no | yes | -
| ✅ | no | both | yes | no | -
| ✅ | no | both | yes | yes | -
| ✅ | no | binderdocker | no | yes | -
| ✅ | no | binderdocker | yes | yes | -
| ❌ | no | binderdocker | no | no | attestation
| ❌ | no | binderdocker | yes | no | attestation
| ❌ | no | login-action | no | no | binderdocker
| ❌ | no | login-action | no | yes | binderdocker
| ❌ | no | login-action | yes | no | binderdocker
| ❌ | no | login-action | yes | yes| binderdocker
| ❌ | yes | both | no | no | attestation
| ❌ | yes | both | no | yes | attestation
| ❌ | yes | both | yes | no | attestation
| ❌ | yes | both | yes | yes | attestation
| ❌ | yes | binderdocker | no | no | attestation
| ❌ | yes | binderdocker | no | yes | login-action
| ❌ | yes | binderdocker | yes | no | attestation
| ❌ | yes | binderdocker | yes | yes | login-action
| ❌ | yes | login-action | no | no | attestation
| ❌ | yes | login-action | no | yes | attestation
| ❌ | yes | login-action | yes | no | attestation
| ❌ | yes | login-action | yes | yes | attestation

The failure reasons are:
- `binderdocker`: pushing fails with `unauthorized: unauthenticated: User cannot be authenticated with the token provided.`
- `attestation`: `No credentials found for registry ghcr.io`
- `login-action`: `Error saving credentials: mkdir $HOME/.docker: permission denied`

### YAML workflow

```yaml
name: Test
on: workflow_dispatch
jobs:
  test-matrix:
    name: >-
      (
      ${{ (matrix.env.DOCKER_CONFIG && 'env') || 'no-env' }} |
      ${{ matrix.first_login }} |
      ${{ (matrix.binderdocker_logout && 'logout') || 'no-logout' }} |
      ${{ (matrix.second_login && 'login') || 'no-login' }}
      )
    strategy:
      fail-fast: false
      matrix:
        env:
          - DOCKER_CONFIG: $HOME/.docker
          - {}
        first_login:
          - login-action
          - binderdocker
          - both
        binderdocker_logout: [ true, false ]
        second_login: [ true, false ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        id: login-action-before
        if: matrix.first_login != 'binderdocker'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Deploy
        id: binder-docker
        uses: RepoDynamics/BinderDocker@main
        with:
          docker_registry: ${{ (matrix.first_login != 'login-action' && 'ghcr.io') || '' }}
          docker_username: ${{ (matrix.first_login != 'login-action' && github.repository_owner) || '' }}
          docker_password: ${{ (matrix.first_login != 'login-action' && secrets.GITHUB_TOKEN) || '' }}
          image_name: ghcr.io/aariam/docker-test
          image_tags: latest
          git_ref: ${{ github.ref }}
          cache_image_tags: latest
          push: True
          verify_public: ${{ (matrix.binderdocker_logout && 'warning') || 'false' }}
      - uses: docker/login-action@v3
        id: login-action-after
        if: matrix.second_login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Attestation
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/aariam/docker-test
          subject-digest: ${{ steps.binder-docker.outputs.image_digest }}
          push-to-registry: 'true'
          show-summary: 'false'
      - name: Summary
        if: always()
        env:
          job_steps: ${{ toJSON(steps) }}
        shell: python
        run: |
          import os
          import json
          
          step_summary = os.environ["GITHUB_STEP_SUMMARY"]
          steps = json.loads(os.environ["job_steps"])
          all_passed = True
          with open(step_summary, "a") as f:
            for step_id, step in steps.items():
              if step["outcome"] == "failure":
                print(f'❌ {step_id}', file=f)
                all_passed = False
            if all_passed:
              print('✅', file=f)
```
