### ISSUE TITLE
Error: Username and password required

### ISSUE THREAD

**Issue by ziazon** [docker/login-action#824]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

We did not make any changes to our secrets or workflows.  we started seeing authentication failures last week, and noticed when looking at the logs that even though we've included the username and password in the `step.with` block, it doesn't get included in the action.  and again, we changed nothing on our end not in code nor in secrets.

### Expected behaviour

when specifying username/password, they are correctly used.

### Actual behaviour

We are seeing this error all of a sudden:
![Image](https://github.com/user-attachments/assets/754da389-21c0-471c-8106-ae5aaeef6d4e)

and yes, we did include the credentials:
```
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
```
we took a look at some old runs of the action and they display it correctly:
![Image](https://github.com/user-attachments/assets/1e9c899d-9c12-4aee-b9fd-6f6dc1bc785d)

### YAML workflow

```yaml
- name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
```

### BuildKit logs

```text

```

**Comment by ziazon** [comment]
this issue had the same problem.  turns out billing was updated to a free account which removes usage of secrets from private repos.

more details here:
https://github.com/docker/login-action/issues/772

**Comment by dadoonet** [comment]
In case someone else hits the same issue as I just did, I'm documenting my findings here:

My code is something like:

```yaml
name: Login to Dockerhub demo

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```

So I have 2 Github secrets in my project settings: `DOCKER_USERNAME` and `DOCKER_PASSWORD`.

All good. This is working correctly anytime I'm pushing a new branch.

But, when dependabot wants to push a change, it reads the secrets from Dependabot secrets.

<img width="328" alt="Image" src="https://github.com/user-attachments/assets/d5ab3df6-5add-43e9-9a9d-0539badff603" />

The stupid mistake I did was to define `DOCKER_USERNAME` and `DOCKER_TOKEN`. Which is not `DOCKER_PASSWORD`.

Which was doing this behavior:

```
Run docker/login-action@v3
  with:
    username: ***
    ecr: auto
    logout: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64
    JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64
Error: Password required
```

By providing `DOCKER_PASSWORD` in the dependabot secrets, I could solve the problem...
And actually, as I did not need to push anything to Docker when building a PR, I just removed the `docker/login-action` from my script...

I hope this could help someone else...
