### ISSUE TITLE
"You have reached your unauthenticated pull rate limit" After login with the action

### ISSUE THREAD

**Issue by royreznik** [docker/login-action#862]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/login-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

So we are using the action as usual, but some time we get an error that related to us not being logged in, although we are,

```
      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: username
          password: ${{ secrets.SECRET }}
```

and we get the following result:

![Image](https://github.com/user-attachments/assets/b8ea336e-e0f2-47c5-8578-8c8e3fd45eab)

And then few second later we get this:
```
Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit
```

### Expected behaviour

-

### Actual behaviour

-

### YAML workflow

```yaml
- name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: username
          password: ${{ secrets.SECRET }}
      - name: build
        id: build
        run: >
          docker run linuxkit/binfmt:v1.0.0


This is ofc a psedu, but it it basically the same
```

### BuildKit logs

```text

```

**Comment by 2lu3** [comment]
same

**Comment by tenjaa** [comment]
I can report the same issue. We are using docker compose via bash:
```
---
name: test
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-findings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: jdx/mise-action@v2
    - run: |
        docker compose up -d --quiet-pull
        [...]
```

![Image](https://github.com/user-attachments/assets/e0192cf5-18bb-47fa-b4c5-08122e5cee81)

**Comment by tenjaa** [comment]
@crazy-max Do you have any link where it states that GitHub hosted runners do NOT have a rate limit applied?
We observed rate limits before and therefore I just added the login now. And we are using a token of a user with a paid license.

**Comment by crazy-max** [comment]
GitHub hosted runners have docker login credentials set up for pulling without rate-limit. You can check it with:

```yaml
      -
        name: Docker config
        run: |
          cat ~/.docker/config.json
```

Should output smth like:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "***"
		}
	}
}
```

> Do you have any link where it states that GitHub hosted runners do NOT have a rate limit applied?

Not sure if there is docs about it but you can ask on https://github.com/docker/hub-feedback/
