### ISSUE TITLE
Give the option to ignore failing logins

### ISSUE THREAD

**Issue by silv-io** [docker/login-action#871]
### Description

It would be nice to have an option to ignore failures resulting from missing credentials.

This can happen, e.g., when you use the login action to avoid rate limiting issues and also receive community contributions in your repository.
When a community contributor triggers a PR workflow run they won't have the secrets available to login into Docker and will cause a failure.

One workaround is to not run that step if those secrets are empty. However, adding a parameter to ignore such failures would be more streamlined.

**Comment by crazy-max** [comment]
In such case you need a condition based on the github event to skip the step:

```yaml
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
