### ISSUE TITLE
Scope of Run Command after Authentication

### ISSUE THREAD

**Issue by dschinkel** [docker/login-action#9]
Can I assume that after I auth successfully here that the next run command takes that auth context?  For example:

```
- name: Login to GCR
  uses: docker/login-action@v1
  with:
    registry: gcr.io
    username: _json_key
    password: ${{ secrets.GCR_JSON_KEY }}
- run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/we-do-tdd:latest
```

I ask because I keep getting this error and I know I'm using a key with Cloud Storage Admin rights and I can't figure out why it keeps rejecting me still if I've authed with that key:
![Screen Shot 2020-09-05 at 6 52 34 PM](https://user-images.githubusercontent.com/338798/92315292-13dd4080-efa9-11ea-812b-9dc76e8432d5.jpg)

![Screen Shot 2020-09-05 at 3 47 37 AM](https://user-images.githubusercontent.com/338798/92315303-569f1880-efa9-11ea-8372-06b3fb378cc9.jpg)

![Screen Shot 2020-09-05 at 3 36 35 AM](https://user-images.githubusercontent.com/338798/92315300-44bd7580-efa9-11ea-9b53-80c00a2ba900.jpg)
