### ISSUE TITLE
Failed to login with username and password or access token.

### ISSUE THREAD

**Issue by Daniele-Tentoni** [docker/login-action#95]
#### Steps to reproduce this issue

1. Use this action in my workflow
2. Add a secret for username and for password, try to change any combinations of those, even with a token, username + password, username + token, email + password, email + token, nothing

#### Expected behaviour

I'm expecting to be authenticated. I don't have any right result message because I haven't one yet.

#### Actual behaviour

I'm receiving this error message:

```
Run docker/login-action@v1
  with:
    username: ***
    password: $***
    logout: true
Logging into Docker Hub...
Error: Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

### Configuration

* Repository URL (if public): https://github.com/Weather-Vortex/iot-weather
* Build URL (if public): https://github.com/Weather-Vortex/iot-weather/actions/runs/1156137707

```yml
push-to-registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: $${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: antonioparolisi/weather-vortex-station

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it]([logs_37.zip](https://github.com/docker/login-action/files/7027885/logs_37.zip)) to this issue.
