### ISSUE TITLE
Ubuntu latest cannot find .docker

### ISSUE THREAD

**Issue by Judahh** [docker/login-action#96]
#### Steps to reproduce this issue

1. Execute action

#### Expected behaviour

Login

#### Actual behaviour

Error: Unable to locate executable file: docker. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### Configuration
```yml
name: Staging

on:
  push:
    branches:
      - "development"
      - "develop"
      - "devel"

jobs:
  build:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: node:10.16-jessie

    steps:
      - name: Check Out Repo
        uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push AUTH
        id: docker_build_auth
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth-s:latest
          build-args: |
            PROJECT_ENV=staging
            SERVICE_NAME=AUTH

      - name: Image digest
        run: echo ${{ steps.docker_build_auth.outputs.digest }}

      - name: Build and push PRODUCT
        id: docker_build_product
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/product-s:latest
          build-args: |
            PROJECT_ENV=staging
            SERVICE_NAME=PRODUCT

      - name: Image digest
        run: echo ${{ steps.docker_build_product.outputs.digest }}

      - name: ZIP
        uses: papeloto/action-zip@master
        with:
          files: "README.md docker-compose.yml"
          dest: staging/latest.zip
          recursive: false

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: staging
          destination_dir: ${{ github.event.repository.name }}/staging
```

### Logs
[logs_4.zip](https://github.com/docker/login-action/files/7039360/logs_4.zip)
