### ISSUE TITLE
Docker related steps after login-action don't work with `no basic auth credentials`

### ISSUE THREAD

**Issue by mdedetrich** [docker/login-action#97]
#### Steps to reproduce this issue

1. Have an already existing docker login using `echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin`
2. Change it so it uses `login-action` github action
3. Create a pull request out of it

#### Expected behaviour

A successful docker-login persists the login information so later `docker-compose` works succesfully

#### Actual behaviour

Docker login happened successfully however the next step in the pipeline `docker-compose up -d` fails to execute with `no basic auth credentials`.

### Configuration

* Repository URL (if public): https://github.com/zalando-nakadi/kanadi/pull/185
* Build URL (if public): https://github.com/zalando-nakadi/kanadi/actions/runs/1169463318

```yml
# This file was automatically generated by sbt-github-actions using the
# githubWorkflowGenerate task. You should add and commit this file to
# your git repository. It goes without saying that you shouldn't edit
# this file by hand! Instead, if you wish to make changes, you should
# change your sbt build configuration to revise the workflow description
# to meet your needs, then regenerate this file.

name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.11, 2.13.4]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Check that workflows are up to date
        run: sbt ++${{ matrix.scala }} githubWorkflowCheck

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Launch Nakadi
        run: docker-compose up -d

      - name: Build project
        run: sbt ++${{ matrix.scala }} clean coverage test

      - name: Upload coverage data to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls

      - name: Shut down Nakadi
        run: docker-compose down
```

### Logs
[logs_71.zip](https://github.com/docker/login-action/files/7052480/logs_71.zip)

**Comment by crazy-max** [comment]
@mdedetrich Looks like docker-compose doesn't use the auth config as it should. Looks similar to:

* https://github.com/joyent/sdc-docker/issues/145
* https://github.com/docker/compose/issues/3037

You could try:

```yaml
      - name: Launch Nakadi
        run: |
          docker-compose pull
          docker-compose up -d
```
